#!/bin/sh

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

while true ; do
  sleep 1
  if [ ! -f /config/cgminer.conf ]; then
    continue
  fi

  lcd-message $(cat /etc/knc-release)
  sleep 1
  # 1m average - for CGMiner
  speed=$(api-cgminer | sed -n -e 's/^.*\[MHS 1m\][^0123456789]\+\([0123456789]\+\).*$/\1/p')
  if [ "x${speed}" = "x" ] ; then
    # 20s average - for BFGMiner
    speed=$(api-cgminer | sed -n -e 's/^.*\[MHS 20s\][^0123456789]\+\([0123456789]\+\).*$/\1/p')
  fi
  lcd-message $speed MHs
done
