#!/bin/sh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

SN=`/bin/dd if=/sys/bus/i2c/devices/3-0050/eeprom bs=32 count=1 skip=1 2>/dev/null`
ID=${SN:1:1}

case $ID in
	1|2|S|G)
		$DIR/monitordcdc.ge
	;;
	E)
		$DIR/monitordcdc.ericsson
	;;
esac
